package iec61850

// #include <iec61850_client.h>
import "C"

// Err get real ied error type
func Err(e C.IedClientError) string {
	switch e {
	case C.IED_ERROR_OK:
		return "IED_ERROR_OK"
	case C.IED_ERROR_NOT_CONNECTED:
		return "IED_ERROR_NOT_CONNECTED"
	case C.IED_ERROR_ALREADY_CONNECTED:
		return "IED_ERROR_ALREADY_CONNECTED"
	case C.IED_ERROR_CONNECTION_LOST:
		return "IED_ERROR_CONNECTION_LOST"
	case C.IED_ERROR_SERVICE_NOT_SUPPORTED:
		return "IED_ERROR_SERVICE_NOT_SUPPORTED"
	case C.IED_ERROR_CONNECTION_REJECTED:
		return "IED_ERROR_CONNECTION_REJECTED"
	case C.IED_ERROR_OUTSTANDING_CALL_LIMIT_REACHED:
		return "IED_ERROR_OUTSTANDING_CALL_LIMIT_REACHED"
	case C.IED_ERROR_USER_PROVIDED_INVALID_ARGUMENT:
		return "IED_ERROR_USER_PROVIDED_INVALID_ARGUMENT"
	case C.IED_ERROR_ENABLE_REPORT_FAILED_DATASET_MISMATCH:
		return "IED_ERROR_ENABLE_REPORT_FAILED_DATASET_MISMATCH"
	case C.IED_ERROR_OBJECT_REFERENCE_INVALID:
		return "IED_ERROR_OBJECT_REFERENCE_INVALID"
	case C.IED_ERROR_UNEXPECTED_VALUE_RECEIVED:
		return "IED_ERROR_UNEXPECTED_VALUE_RECEIVED"
	case C.IED_ERROR_TIMEOUT:
		return "IED_ERROR_TIMEOUT"
	case C.IED_ERROR_ACCESS_DENIED:
		return "IED_ERROR_ACCESS_DENIED"
	case C.IED_ERROR_OBJECT_DOES_NOT_EXIST:
		return "IED_ERROR_OBJECT_DOES_NOT_EXIST"
	case C.IED_ERROR_OBJECT_EXISTS:
		return "IED_ERROR_OBJECT_EXISTS"
	case C.IED_ERROR_OBJECT_ACCESS_UNSUPPORTED:
		return "IED_ERROR_OBJECT_ACCESS_UNSUPPORTED"
	case C.IED_ERROR_TYPE_INCONSISTENT:
		return "IED_ERROR_TYPE_INCONSISTENT"
	case C.IED_ERROR_TEMPORARILY_UNAVAILABLE:
		return "IED_ERROR_TEMPORARILY_UNAVAILABLE"
	case C.IED_ERROR_OBJECT_UNDEFINED:
		return "IED_ERROR_OBJECT_UNDEFINED"
	case C.IED_ERROR_INVALID_ADDRESS:
		return "IED_ERROR_INVALID_ADDRESS"
	case C.IED_ERROR_HARDWARE_FAULT:
		return "IED_ERROR_HARDWARE_FAULT"
	case C.IED_ERROR_TYPE_UNSUPPORTED:
		return "IED_ERROR_TYPE_UNSUPPORTED"
	case C.IED_ERROR_OBJECT_ATTRIBUTE_INCONSISTENT:
		return "IED_ERROR_OBJECT_ATTRIBUTE_INCONSISTENT"
	case C.IED_ERROR_OBJECT_VALUE_INVALID:
		return "IED_ERROR_OBJECT_VALUE_INVALID"
	case C.IED_ERROR_OBJECT_INVALIDATED:
		return "IED_ERROR_OBJECT_INVALIDATED"
	case C.IED_ERROR_MALFORMED_MESSAGE:
		return "IED_ERROR_MALFORMED_MESSAGE"
	case C.IED_ERROR_SERVICE_NOT_IMPLEMENTED:
		return "IED_ERROR_SERVICE_NOT_IMPLEMENTED"
	case C.IED_ERROR_UNKNOWN:
		return "IED_ERROR_UNKNOWN"
	}

	return "IED_ERROR_UNDEFINED"
}
